parent: classic # Nom du thème parent
name: Alain # Identifiant de votre thème enfant, identique au dossier
display-name: Theme 2 # Description du thème
version: 1.0.0 # Version en cas de mise à jour
assets:
  use_parent_assets: true 